name = "Holiday Server Pack"
author = "cassiancc"
version = "0.106.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ee41f9e648a99cb6f42df58ed233ab3809cce5e85e1a228683c5ab8ccf0a662"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
