name = "Holiday Server Pack"
author = "cassiancc"
version = "0.159.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13c9584559c6c7491a38a3970404b708fd8be136e04a597140a945a6df026bea"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
