name = "Holiday Server Pack"
author = "cassiancc"
version = "0.94.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "449be17949f2b28ed76fd72b1ae95153edb5998a4db5dfdf6cfaf6492126d371"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
