name = "Holiday Server Pack"
author = "cassiancc"
version = "0.94.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "183bcc8cc112ee30f51c84d0a746aa4ccbca9bee87d7701014100682579d7dd7"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
