name = "Holiday Server Pack"
author = "cassiancc"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f96be4527496cc65971df06126dd3f2cfedfd650864843fb841e66468057490a"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
