name = "Holiday Server Pack"
author = "cassiancc"
version = "0.210.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "019e0de597d4e5948f9e611f988210c63e2e8a0c2e8501bc264bc8cbf5e33dbb"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
