name = "Holiday Server Pack"
author = "cassiancc"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c22420aaf6fd3840045c3281004676ffef9b169380862eea548b9634a35a5dfb"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
