name = "Holiday Server Pack"
author = "cassiancc"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bad5b1042cc1fcbbaf202d029518477ee8663fa66a4f1a4f4ef7b51dc8c9166b"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
