name = "Holiday Server Pack"
author = "cassiancc"
version = "0.104.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2ffb19a2083f5d69fe90c4a19f82a4c8e1c95ec1470873485256ceec30fc914"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
