name = "Holiday Server Pack"
author = "cassiancc"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ae561d1da0f9b09ee87a3860df315633715d558a40287569d41bff519866d0d"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
