name = "Holiday Server Pack"
author = "cassiancc"
version = "0.76.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94365932cd65d40a122eeebf50bf8ab2cadfadc6525d349ffe26bdc2acb52ff6"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
